FROM ubuntu:16.04

# common environment variables
ENV KATALON_ROOT_DIR=/katalon
ENV KATALON_BASE_ROOT_DIR=/katalon/base
ENV KATALON_MAKE_EXECUTABLE_SCRIPT=$KATALON_BASE_ROOT_DIR/make_executable.sh
ENV KATALON_CLEAN_UP_SCRIPT=$KATALON_BASE_ROOT_DIR/cleanup.sh
ENV KATALON_VERSION_FILE=/katalon/version

ENV GRADLE_HOME=/opt/gradle
ENV GRADLE_BIN=$GRADLE_HOME/bin

ENV DISPLAY=:99
ENV DISPLAY_CONFIGURATION=1024x768x24

# copy scripts
RUN mkdir -p $KATALON_BASE_ROOT_DIR
WORKDIR $KATALON_BASE_ROOT_DIR

ADD ./src ./
RUN chmod a+x $KATALON_MAKE_EXECUTABLE_SCRIPT
RUN $KATALON_MAKE_EXECUTABLE_SCRIPT .

RUN ./index.sh

RUN $KATALON_CLEAN_UP_SCRIPT

ENV PATH "$PATH:$GRADLE_BIN"

WORKDIR /