name: "[Dockerhub] Promote Docker Images to Latest Tag"

on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Original tag (e.g: "10.3.0")'
        required: true
        type: string
      
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        run: echo "MAJOR_VERSION=$(echo "${{ inputs.VERSION }}" | cut -d. -f1)" >> $GITHUB_ENV

      - name: print env
        run: printenv | grep MAJOR_VERSION # only print MAJOR_VERSION to prevent exposing sensitive credentials

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull the original images
        run: |
          docker pull katalonstudio/katalon:${{ inputs.VERSION }}
          docker pull katalonstudio/katalon:${{ inputs.VERSION }}-slim

      - name: Tag the original images to latest
        run: |
          docker tag katalonstudio/katalon:${{ inputs.VERSION }} katalonstudio/katalon:$MAJOR_VERSION-latest
          docker tag katalonstudio/katalon:${{ inputs.VERSION }} katalonstudio/katalon:latest

          docker tag katalonstudio/katalon:${{ inputs.VERSION }}-slim katalonstudio/katalon:$MAJOR_VERSION-latest-slim
          docker tag katalonstudio/katalon:${{ inputs.VERSION }}-slim katalonstudio/katalon:latest-slim

      - name: Push the latest images
        run: |
          docker push katalonstudio/katalon:$MAJOR_VERSION-latest
          docker push katalonstudio/katalon:latest

          docker push katalonstudio/katalon:$MAJOR_VERSION-latest-slim
          docker push katalonstudio/katalon:latest-slim
