name: Default Docker Image
on:
  push:
    branches:
      - STUIDO-6141
# on:
#   workflow_dispatch:
#     inputs:
#       KS_VERSION:
#         description: 'Katalon Studio version (e.g: "9.5.0")'
#         required: true
#       DOCKER_IMAGE_TAG:
#         description: 'Docker image tag (e.g: "9.5.0")'
#         required: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
        KS_VERSION: '9.7.0-rc1'
        DOCKER_IMAGE_TAG: '9.7.0-rc1'
        # KS_VERSION: ${{ inputs.KS_VERSION }}
        # DOCKER_IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name : Prepare docker install 
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo apt -y install jq
    - name:  Build
      run: |
        chmod u+x ./build/*.sh
        ./build/clean.sh $KS_VERSION
        ./build/build.sh $KS_VERSION
    - name: Tag Docker image with commit ID
      run: docker tag katalon-katalon 002582244933.dkr.ecr.us-east-1.amazonaws.com/katalon-studio:$DOCKER_IMAGE_TAG
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::002582244933:role/katalon-github-oidc-federation
        role-session-name: github-actions
        aws-region: us-east-1
        mask-aws-account-id: 'no'
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    - name: Push Docker image to ECR
      run: docker push 002582244933.dkr.ecr.us-east-1.amazonaws.com/katalon-studio:$DOCKER_IMAGE_TAG
